apiVersion: v1
kind: Service
metadata:
  name: product-app
  labels:
    app: product-app
    expose: "true"
    hystrix.enabled: "true"
spec:
  type: "LoadBalancer"
  selector:
    app: product-app
    hystrix.enabled: "true"
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
